version: '3.9'
services:
    # Frontend incl. Masterportal configuration for the storytelling tool
    stt-frontend:
        container_name: stt-frontend
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - proxy

networks:
    proxy:
        external: true
