version: '3.9'
services:
  # Frontend incl. Masterportal configuration and both the storytelling and the data collection add-on
  mobility-frontend:
    container_name: mobility-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
