version: '3.9'
services:
    # Frontend incl. Masterportal configuration for the storytelling tool
    stt-frontend:
        container_name: stt-frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mobility-frontend-re2.entrypoints=https"
            - "traefik.http.routers.mobility-frontend-re2.rule=Host(`stt.cut.hcu-hamburg.de`)"
            - "traefik.http.routers.mobility-frontend-re2.tls=true"
            - "traefik.http.routers.mobility-frontend-re2.tls.certresolver=lets-encr"

networks:
    proxy:
        external: true
