version: '3.9'
services:
    # Frontend incl. Masterportal configuration for the storytelling tool
    stt-frontend:
        container_name: stt-frontend
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.stt-frontend.entrypoints=https"
            - "traefik.http.routers.stt-frontend.rule=Host(`stt.cut.hcu-hamburg.de`)"
            - "traefik.http.routers.stt-frontend.tls=true"
            - "traefik.http.routers.stt-frontend.tls.certresolver=lets-encr"
            - "traefik.http.middlewares.my-authenticator.basicauth.users=testuser:$$2a$$12$$j7PFu2c/yy4Ng.8xHLZ1OOmn.G8IbzGgaiLdlSvjc.hx8NKYlniUK"
            - "traefik.http.routers.stt-frontend.middlewares=my-authenticator@docker"

networks:
    proxy:
        external: true
