version: '3.9'
services:
    # Frontend incl. Masterportal configuration for the storytelling tool
    stt-frontend:
        container_name: stt-frontend-summit
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.stt-summit.entrypoints=https"
            - "traefik.http.routers.stt-summit.rule=Host(`summit.cut.hcu-hamburg.de`)"
            - "traefik.http.routers.stt-summit.tls=true"
            #- "traefik.http.routers.stt-frontend.tls.certresolver=lets-encr"

networks:
    proxy:
        external: true
