version: '3.9'
services:
  # Frontend incl. Masterportal configuration and both the storytelling and the data collection add-on
  mobility-frontend:
    container_name: mobility-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://localhost:8080
        TEST_ENV: false
    ports:
      - '80:80'
